-- Email verification tokens (Phase 0 auth). One-shot, expiring tokens; rows are
-- deleted on successful verification or replaced on resend.

CREATE TABLE email_verification_tokens (
    token      CHAR(64)        NOT NULL, -- hex of 32 random bytes, generated by the API
    user_id    BIGINT UNSIGNED NOT NULL,
    expires_at TIMESTAMP       NOT NULL,
    created_at TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (token),
    KEY idx_evt_user (user_id),
    CONSTRAINT fk_evt_user FOREIGN KEY (user_id) REFERENCES users (id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
