-- Starter interest taxonomy (ARCHITECTURE.md §5) — drives transparent matching.
-- Extend freely; slugs are the stable API identifier, labels are display-only.

INSERT INTO interests (slug, label) VALUES
    ('hiking', 'Hiking'),
    ('climbing', 'Climbing'),
    ('running', 'Running'),
    ('cycling', 'Cycling'),
    ('swimming', 'Swimming'),
    ('yoga', 'Yoga'),
    ('gym', 'Gym'),
    ('dancing', 'Dancing'),
    ('cooking', 'Cooking'),
    ('baking', 'Baking'),
    ('coffee', 'Coffee'),
    ('wine', 'Wine'),
    ('craft-beer', 'Craft beer'),
    ('foodie', 'Food & restaurants'),
    ('travel', 'Travel'),
    ('camping', 'Camping'),
    ('photography', 'Photography'),
    ('art', 'Art'),
    ('museums', 'Museums'),
    ('live-music', 'Live music'),
    ('playing-music', 'Playing music'),
    ('movies', 'Movies'),
    ('theatre', 'Theatre'),
    ('reading', 'Reading'),
    ('writing', 'Writing'),
    ('gaming', 'Gaming'),
    ('board-games', 'Board games'),
    ('tech', 'Technology'),
    ('science', 'Science'),
    ('history', 'History'),
    ('languages', 'Languages'),
    ('volunteering', 'Volunteering'),
    ('gardening', 'Gardening'),
    ('pets', 'Pets'),
    ('dogs', 'Dogs'),
    ('cats', 'Cats');
